version: "3"

services:
  database-pokemon:
    container_name: database-pokemon
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pokedex}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-pokedex}
    ports:
      - "5432:5432"
    volumes:
      - db-diesel:/var/lib/postgresql/data:rw
  diesel-pokemon:
    container_name: diesel-pokemon
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-pokedex}:${POSTGRES_PASSWORD:-password}@database-pokemon/${POSTGRES_DB:-pokedex}
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/diesel-pokemon
      - diesel-pokemon-target:/diesel/target
    depends_on:
      - database-pokemon

volumes:
  # postgres data
  db-diesel:
  # rust data
  diesel-pokemon-target:
