ALTER TABLE pokemon
ALTER COLUMN hp DROP NOT NULL;
ALTER TABLE pokemon
ALTER COLUMN attack DROP NOT NULL;
ALTER TABLE pokemon
ALTER COLUMN defense DROP NOT NULL;
ALTER TABLE pokemon
ALTER COLUMN special_attack DROP NOT NULL;
ALTER TABLE pokemon
ALTER COLUMN special_defense DROP NOT NULL;
ALTER TABLE pokemon
ALTER COLUMN speed DROP NOT NULL;