ALTER TABLE pokemon
ALTER COLUMN hp SET NOT NULL;
ALTER TABLE pokemon
ALTER COLUMN attack SET NOT NULL;
ALTER TABLE pokemon
ALTER COLUMN defense SET NOT NULL;
ALTER TABLE pokemon
ALTER COLUMN special_attack SET NOT NULL;
ALTER TABLE pokemon
ALTER COLUMN special_defense SET NOT NULL;
ALTER TABLE pokemon
ALTER COLUMN speed SET NOT NULL;